/**
 * @file test_moc.c
 * @brief Test program for MOC-generated code
 *
 * This program tests the wrapper functions and tool table generated by MOC.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>

/* Include the generated header */
#include "tools_gen.h"

/* Include cJSON for result parsing */
#include "cJSON.h"

/*============================================================================
 * Test Helpers
 *============================================================================*/

static int test_count = 0;
static int pass_count = 0;

#define TEST(name) \
    do { \
        printf("Test: %s... ", name); \
        test_count++; \
    } while(0)

#define PASS() \
    do { \
        printf("PASS\n"); \
        pass_count++; \
    } while(0)

#define FAIL(msg) \
    do { \
        printf("FAIL: %s\n", msg); \
    } while(0)

/*============================================================================
 * Test Cases
 *============================================================================*/

void test_tool_count(void) {
    TEST("Tool count");
    
    size_t count = ac_tool_count();
    /* We defined 5 AC_TOOL_META functions (get_weather excluded from test for now) */
    if (count >= 4 && count <= 5) {
        PASS();
    } else {
        char msg[64];
        snprintf(msg, sizeof(msg), "Expected 4-5 tools, got %zu", count);
        FAIL(msg);
    }
}

void test_tool_table_structure(void) {
    TEST("Tool table structure");
    
    /* Check that all entries have required fields */
    for (size_t i = 0; G_TOOL_TABLE[i].name != NULL; i++) {
        if (G_TOOL_TABLE[i].schema == NULL || G_TOOL_TABLE[i].wrapper == NULL) {
            FAIL("Tool entry missing schema or wrapper");
            return;
        }
    }
    PASS();
}

void test_add_two_numbers_wrapper(void) {
    TEST("add_two_numbers wrapper");
    
    /* Find the wrapper */
    ac_tool_wrapper_t wrapper = NULL;
    for (size_t i = 0; G_TOOL_TABLE[i].name != NULL; i++) {
        if (strcmp(G_TOOL_TABLE[i].name, "add_two_numbers") == 0) {
            wrapper = G_TOOL_TABLE[i].wrapper;
            break;
        }
    }
    
    if (!wrapper) {
        FAIL("Wrapper not found");
        return;
    }
    
    /* Call with JSON arguments */
    char *result = wrapper("{\"a\": 5, \"b\": 3}");
    if (!result) {
        FAIL("Wrapper returned NULL");
        return;
    }
    
    /* Parse result */
    cJSON *json = cJSON_Parse(result);
    free(result);
    
    if (!json) {
        FAIL("Failed to parse result JSON");
        return;
    }
    
    cJSON *value = cJSON_GetObjectItem(json, "result");
    if (!value || !cJSON_IsNumber(value)) {
        cJSON_Delete(json);
        FAIL("Result field missing or not a number");
        return;
    }
    
    int res = (int)cJSON_GetNumberValue(value);
    cJSON_Delete(json);
    
    if (res == 8) {
        PASS();
    } else {
        char msg[64];
        snprintf(msg, sizeof(msg), "Expected 8, got %d", res);
        FAIL(msg);
    }
}

void test_get_weather_wrapper(void) {
    TEST("get_weather wrapper");
    
    /* Find the wrapper */
    ac_tool_wrapper_t wrapper = NULL;
    for (size_t i = 0; G_TOOL_TABLE[i].name != NULL; i++) {
        if (strcmp(G_TOOL_TABLE[i].name, "get_weather") == 0) {
            wrapper = G_TOOL_TABLE[i].wrapper;
            break;
        }
    }
    
    if (!wrapper) {
        FAIL("Wrapper not found");
        return;
    }
    
    /* Call with JSON arguments */
    char *result = wrapper("{\"place\": \"Tokyo\"}");
    if (!result) {
        FAIL("Wrapper returned NULL");
        return;
    }
    
    /* Parse result */
    cJSON *json = cJSON_Parse(result);
    free(result);
    
    if (!json) {
        FAIL("Failed to parse result JSON");
        return;
    }
    
    cJSON *value = cJSON_GetObjectItem(json, "result");
    if (!value || !cJSON_IsString(value)) {
        cJSON_Delete(json);
        FAIL("Result field missing or not a string");
        return;
    }
    
    /* Just check that we got a string result */
    const char *weather = cJSON_GetStringValue(value);
    cJSON_Delete(json);
    
    if (weather && strlen(weather) > 0) {
        PASS();
    } else {
        FAIL("Empty weather result");
    }
}

void test_is_positive_wrapper(void) {
    TEST("is_positive wrapper");
    
    /* Find the wrapper */
    ac_tool_wrapper_t wrapper = NULL;
    for (size_t i = 0; G_TOOL_TABLE[i].name != NULL; i++) {
        if (strcmp(G_TOOL_TABLE[i].name, "is_positive") == 0) {
            wrapper = G_TOOL_TABLE[i].wrapper;
            break;
        }
    }
    
    if (!wrapper) {
        FAIL("Wrapper not found");
        return;
    }
    
    /* Test positive number */
    char *result = wrapper("{\"value\": 42}");
    if (!result) {
        FAIL("Wrapper returned NULL");
        return;
    }
    
    cJSON *json = cJSON_Parse(result);
    free(result);
    
    if (!json) {
        FAIL("Failed to parse result JSON");
        return;
    }
    
    cJSON *value = cJSON_GetObjectItem(json, "result");
    bool is_pos = cJSON_IsTrue(value);
    cJSON_Delete(json);
    
    if (is_pos) {
        PASS();
    } else {
        FAIL("Expected true for positive number");
    }
}

void test_error_handling(void) {
    TEST("Error handling (invalid JSON)");
    
    /* Find any wrapper */
    ac_tool_wrapper_t wrapper = G_TOOL_TABLE[0].wrapper;
    if (!wrapper) {
        FAIL("No wrapper available");
        return;
    }
    
    /* Call with invalid JSON */
    char *result = wrapper("not valid json");
    if (!result) {
        FAIL("Wrapper returned NULL instead of error");
        return;
    }
    
    /* Should contain error field */
    cJSON *json = cJSON_Parse(result);
    free(result);
    
    if (!json) {
        FAIL("Failed to parse error response");
        return;
    }
    
    cJSON *error = cJSON_GetObjectItem(json, "error");
    cJSON_Delete(json);
    
    if (error && cJSON_IsString(error)) {
        PASS();
    } else {
        FAIL("Expected error field in response");
    }
}

void test_schema_format(void) {
    TEST("JSON Schema format");
    
    /* Parse one of the schemas */
    const char *schema = G_TOOL_TABLE[0].schema;
    if (!schema) {
        FAIL("No schema available");
        return;
    }
    
    cJSON *json = cJSON_Parse(schema);
    if (!json) {
        FAIL("Failed to parse schema JSON");
        return;
    }
    
    /* Check required fields */
    cJSON *type = cJSON_GetObjectItem(json, "type");
    cJSON *func = cJSON_GetObjectItem(json, "function");
    
    if (!type || !cJSON_IsString(type) || strcmp(cJSON_GetStringValue(type), "function") != 0) {
        cJSON_Delete(json);
        FAIL("Schema type should be 'function'");
        return;
    }
    
    if (!func || !cJSON_IsObject(func)) {
        cJSON_Delete(json);
        FAIL("Schema missing 'function' object");
        return;
    }
    
    cJSON *name = cJSON_GetObjectItem(func, "name");
    cJSON *desc = cJSON_GetObjectItem(func, "description");
    cJSON *params = cJSON_GetObjectItem(func, "parameters");
    
    if (!name || !cJSON_IsString(name)) {
        cJSON_Delete(json);
        FAIL("Function schema missing 'name'");
        return;
    }
    
    if (!params || !cJSON_IsObject(params)) {
        cJSON_Delete(json);
        FAIL("Function schema missing 'parameters'");
        return;
    }
    
    cJSON_Delete(json);
    PASS();
}

/*============================================================================
 * Main
 *============================================================================*/

int main(void) {
    printf("=== MOC Generated Code Tests ===\n\n");
    
    test_tool_count();
    test_tool_table_structure();
    test_add_two_numbers_wrapper();
    test_get_weather_wrapper();
    test_is_positive_wrapper();
    test_error_handling();
    test_schema_format();
    
    printf("\n=== Results ===\n");
    printf("Passed: %d/%d\n", pass_count, test_count);
    
    return (pass_count == test_count) ? 0 : 1;
}
