# gen_prompts.cmake
# Converts prompt .txt files to embedded C strings
#
# Input variables:
#   PROMPT_DIR - Directory containing prompts/system/ and prompts/tools/
#   OUTPUT_C   - Output .c file path
#   OUTPUT_H   - Output .h file path

cmake_minimum_required(VERSION 3.15)

# Helper function to escape string for C
function(escape_for_c INPUT_STRING OUTPUT_VAR)
    # Escape backslashes first
    string(REPLACE "\\" "\\\\" result "${INPUT_STRING}")
    # Escape double quotes
    string(REPLACE "\"" "\\\"" result "${result}")
    # Handle newlines - split into lines and rejoin with \n
    string(REPLACE "\n" "\\n\"\n    \"" result "${result}")
    set(${OUTPUT_VAR} "${result}" PARENT_SCOPE)
endfunction()

# Helper function to convert filename to C identifier
function(filename_to_identifier FILENAME OUTPUT_VAR)
    get_filename_component(name_we "${FILENAME}" NAME_WE)
    # Replace hyphens and dots with underscores
    string(REPLACE "-" "_" result "${name_we}")
    string(REPLACE "." "_" result "${result}")
    # Convert to uppercase
    string(TOUPPER "${result}" result)
    set(${OUTPUT_VAR} "${result}" PARENT_SCOPE)
endfunction()

# Start building output
set(C_CONTENT "/**\n * @file prompts_gen.c\n * @brief Auto-generated embedded prompts\n * DO NOT EDIT - Generated by gen_prompts.cmake\n */\n\n#include \"prompts_gen.h\"\n#include <stddef.h>\n\n")
set(H_CONTENT "/**\n * @file prompts_gen.h\n * @brief Auto-generated embedded prompts header\n * DO NOT EDIT - Generated by gen_prompts.cmake\n */\n\n#ifndef PROMPTS_GEN_H\n#define PROMPTS_GEN_H\n\n#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n")

# Process system prompts
set(H_CONTENT "${H_CONTENT}/* System Prompts */\n")
file(GLOB SYSTEM_FILES "${PROMPT_DIR}/system/*.txt")
set(SYSTEM_PROMPT_LIST "")

foreach(FILE ${SYSTEM_FILES})
    get_filename_component(filename "${FILE}" NAME)
    filename_to_identifier("${filename}" IDENTIFIER)
    
    # Read file content
    file(READ "${FILE}" FILE_CONTENT)
    escape_for_c("${FILE_CONTENT}" ESCAPED_CONTENT)
    
    # Add to C file
    set(C_CONTENT "${C_CONTENT}const char PROMPT_SYSTEM_${IDENTIFIER}[] =\n    \"${ESCAPED_CONTENT}\";\n\n")
    
    # Add to H file
    set(H_CONTENT "${H_CONTENT}extern const char PROMPT_SYSTEM_${IDENTIFIER}[];\n")
    
    # Build list entry
    get_filename_component(name_we "${FILE}" NAME_WE)
    set(SYSTEM_PROMPT_LIST "${SYSTEM_PROMPT_LIST}    { \"${name_we}\", PROMPT_SYSTEM_${IDENTIFIER} },\n")
endforeach()

# Process tool prompts
set(H_CONTENT "${H_CONTENT}\n/* Tool Prompts */\n")
file(GLOB TOOL_FILES "${PROMPT_DIR}/tools/*.txt")
set(TOOL_PROMPT_LIST "")

foreach(FILE ${TOOL_FILES})
    get_filename_component(filename "${FILE}" NAME)
    filename_to_identifier("${filename}" IDENTIFIER)
    
    # Read file content
    file(READ "${FILE}" FILE_CONTENT)
    escape_for_c("${FILE_CONTENT}" ESCAPED_CONTENT)
    
    # Add to C file
    set(C_CONTENT "${C_CONTENT}const char PROMPT_TOOL_${IDENTIFIER}[] =\n    \"${ESCAPED_CONTENT}\";\n\n")
    
    # Add to H file
    set(H_CONTENT "${H_CONTENT}extern const char PROMPT_TOOL_${IDENTIFIER}[];\n")
    
    # Build list entry
    get_filename_component(name_we "${FILE}" NAME_WE)
    set(TOOL_PROMPT_LIST "${TOOL_PROMPT_LIST}    { \"${name_we}\", PROMPT_TOOL_${IDENTIFIER} },\n")
endforeach()

# Add lookup structures
set(H_CONTENT "${H_CONTENT}\n/* Prompt Lookup */\ntypedef struct {\n    const char *name;\n    const char *content;\n} prompt_entry_t;\n\nextern const prompt_entry_t SYSTEM_PROMPTS[];\nextern const int SYSTEM_PROMPTS_COUNT;\n\nextern const prompt_entry_t TOOL_PROMPTS[];\nextern const int TOOL_PROMPTS_COUNT;\n\n")

# Add lookup arrays to C file
list(LENGTH SYSTEM_FILES SYSTEM_COUNT)
list(LENGTH TOOL_FILES TOOL_COUNT)

set(C_CONTENT "${C_CONTENT}/* System Prompt Lookup Table */\nconst prompt_entry_t SYSTEM_PROMPTS[] = {\n${SYSTEM_PROMPT_LIST}    { NULL, NULL }\n};\nconst int SYSTEM_PROMPTS_COUNT = ${SYSTEM_COUNT};\n\n")

set(C_CONTENT "${C_CONTENT}/* Tool Prompt Lookup Table */\nconst prompt_entry_t TOOL_PROMPTS[] = {\n${TOOL_PROMPT_LIST}    { NULL, NULL }\n};\nconst int TOOL_PROMPTS_COUNT = ${TOOL_COUNT};\n")

# Finish header
set(H_CONTENT "${H_CONTENT}#ifdef __cplusplus\n}\n#endif\n\n#endif /* PROMPTS_GEN_H */\n")

# Write output files
file(WRITE "${OUTPUT_C}" "${C_CONTENT}")
file(WRITE "${OUTPUT_H}" "${H_CONTENT}")

message(STATUS "Generated prompts: ${SYSTEM_COUNT} system, ${TOOL_COUNT} tool prompts")
